/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitorsRouteImport } from './routes/visitors'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NRouteImport } from './routes/n'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as CruiseRouteImport } from './routes/cruise'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as USlugRouteImport } from './routes/u.$slug'
import { Route as MessagesIdRouteImport } from './routes/messages.$id'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalSubprocessorsRouteImport } from './routes/legal.subprocessors'
import { Route as LegalSecurityIncidentsRouteImport } from './routes/legal.security-incidents'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalDsaRouteImport } from './routes/legal.dsa'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalCommunityRouteImport } from './routes/legal.community'
import { Route as LegalBusinessTermsRouteImport } from './routes/legal.business-terms'
import { Route as GroupsIdRouteImport } from './routes/groups.$id'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as AdvertiseNewRouteImport } from './routes/advertise.new'
import { Route as ApiPublicGooglePlayRtdnRouteImport } from './routes/api/public/google-play-rtdn'

const VisitorsRoute = VisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NRoute = NRouteImport.update({
  id: '/n',
  path: '/n',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const CruiseRoute = CruiseRouteImport.update({
  id: '/cruise',
  path: '/cruise',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const USlugRoute = USlugRouteImport.update({
  id: '/u/$slug',
  path: '/u/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSubprocessorsRoute = LegalSubprocessorsRouteImport.update({
  id: '/legal/subprocessors',
  path: '/legal/subprocessors',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSecurityIncidentsRoute = LegalSecurityIncidentsRouteImport.update({
  id: '/legal/security-incidents',
  path: '/legal/security-incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDsaRoute = LegalDsaRouteImport.update({
  id: '/legal/dsa',
  path: '/legal/dsa',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCommunityRoute = LegalCommunityRouteImport.update({
  id: '/legal/community',
  path: '/legal/community',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalBusinessTermsRoute = LegalBusinessTermsRouteImport.update({
  id: '/legal/business-terms',
  path: '/legal/business-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIdRoute = GroupsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GroupsRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const AdvertiseNewRoute = AdvertiseNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdvertiseRoute,
} as any)
const ApiPublicGooglePlayRtdnRoute = ApiPublicGooglePlayRtdnRouteImport.update({
  id: '/api/public/google-play-rtdn',
  path: '/api/public/google-play-rtdn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advertise': typeof AdvertiseRouteWithChildren
  '/auth': typeof AuthRoute
  '/blocked': typeof BlockedRoute
  '/business': typeof BusinessRoute
  '/cruise': typeof CruiseRoute
  '/discover': typeof DiscoverRoute
  '/events': typeof EventsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/groups': typeof GroupsRouteWithChildren
  '/n': typeof NRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/visitors': typeof VisitorsRoute
  '/advertise/new': typeof AdvertiseNewRoute
  '/events/$id': typeof EventsIdRoute
  '/groups/$id': typeof GroupsIdRoute
  '/legal/business-terms': typeof LegalBusinessTermsRoute
  '/legal/community': typeof LegalCommunityRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/dsa': typeof LegalDsaRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/security-incidents': typeof LegalSecurityIncidentsRoute
  '/legal/subprocessors': typeof LegalSubprocessorsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/messages/$id': typeof MessagesIdRoute
  '/u/$slug': typeof USlugRoute
  '/messages/': typeof MessagesIndexRoute
  '/api/public/google-play-rtdn': typeof ApiPublicGooglePlayRtdnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advertise': typeof AdvertiseRouteWithChildren
  '/auth': typeof AuthRoute
  '/blocked': typeof BlockedRoute
  '/business': typeof BusinessRoute
  '/cruise': typeof CruiseRoute
  '/discover': typeof DiscoverRoute
  '/events': typeof EventsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/groups': typeof GroupsRouteWithChildren
  '/n': typeof NRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/visitors': typeof VisitorsRoute
  '/advertise/new': typeof AdvertiseNewRoute
  '/events/$id': typeof EventsIdRoute
  '/groups/$id': typeof GroupsIdRoute
  '/legal/business-terms': typeof LegalBusinessTermsRoute
  '/legal/community': typeof LegalCommunityRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/dsa': typeof LegalDsaRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/security-incidents': typeof LegalSecurityIncidentsRoute
  '/legal/subprocessors': typeof LegalSubprocessorsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/messages/$id': typeof MessagesIdRoute
  '/u/$slug': typeof USlugRoute
  '/messages': typeof MessagesIndexRoute
  '/api/public/google-play-rtdn': typeof ApiPublicGooglePlayRtdnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advertise': typeof AdvertiseRouteWithChildren
  '/auth': typeof AuthRoute
  '/blocked': typeof BlockedRoute
  '/business': typeof BusinessRoute
  '/cruise': typeof CruiseRoute
  '/discover': typeof DiscoverRoute
  '/events': typeof EventsRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/groups': typeof GroupsRouteWithChildren
  '/n': typeof NRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/visitors': typeof VisitorsRoute
  '/advertise/new': typeof AdvertiseNewRoute
  '/events/$id': typeof EventsIdRoute
  '/groups/$id': typeof GroupsIdRoute
  '/legal/business-terms': typeof LegalBusinessTermsRoute
  '/legal/community': typeof LegalCommunityRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/dsa': typeof LegalDsaRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/security-incidents': typeof LegalSecurityIncidentsRoute
  '/legal/subprocessors': typeof LegalSubprocessorsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/messages/$id': typeof MessagesIdRoute
  '/u/$slug': typeof USlugRoute
  '/messages/': typeof MessagesIndexRoute
  '/api/public/google-play-rtdn': typeof ApiPublicGooglePlayRtdnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/advertise'
    | '/auth'
    | '/blocked'
    | '/business'
    | '/cruise'
    | '/discover'
    | '/events'
    | '/favorites'
    | '/groups'
    | '/n'
    | '/notifications'
    | '/onboarding'
    | '/premium'
    | '/profile'
    | '/reset-password'
    | '/safety'
    | '/settings'
    | '/visitors'
    | '/advertise/new'
    | '/events/$id'
    | '/groups/$id'
    | '/legal/business-terms'
    | '/legal/community'
    | '/legal/cookies'
    | '/legal/dsa'
    | '/legal/privacy'
    | '/legal/security-incidents'
    | '/legal/subprocessors'
    | '/legal/terms'
    | '/messages/$id'
    | '/u/$slug'
    | '/messages/'
    | '/api/public/google-play-rtdn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/advertise'
    | '/auth'
    | '/blocked'
    | '/business'
    | '/cruise'
    | '/discover'
    | '/events'
    | '/favorites'
    | '/groups'
    | '/n'
    | '/notifications'
    | '/onboarding'
    | '/premium'
    | '/profile'
    | '/reset-password'
    | '/safety'
    | '/settings'
    | '/visitors'
    | '/advertise/new'
    | '/events/$id'
    | '/groups/$id'
    | '/legal/business-terms'
    | '/legal/community'
    | '/legal/cookies'
    | '/legal/dsa'
    | '/legal/privacy'
    | '/legal/security-incidents'
    | '/legal/subprocessors'
    | '/legal/terms'
    | '/messages/$id'
    | '/u/$slug'
    | '/messages'
    | '/api/public/google-play-rtdn'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/advertise'
    | '/auth'
    | '/blocked'
    | '/business'
    | '/cruise'
    | '/discover'
    | '/events'
    | '/favorites'
    | '/groups'
    | '/n'
    | '/notifications'
    | '/onboarding'
    | '/premium'
    | '/profile'
    | '/reset-password'
    | '/safety'
    | '/settings'
    | '/visitors'
    | '/advertise/new'
    | '/events/$id'
    | '/groups/$id'
    | '/legal/business-terms'
    | '/legal/community'
    | '/legal/cookies'
    | '/legal/dsa'
    | '/legal/privacy'
    | '/legal/security-incidents'
    | '/legal/subprocessors'
    | '/legal/terms'
    | '/messages/$id'
    | '/u/$slug'
    | '/messages/'
    | '/api/public/google-play-rtdn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdvertiseRoute: typeof AdvertiseRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlockedRoute: typeof BlockedRoute
  BusinessRoute: typeof BusinessRoute
  CruiseRoute: typeof CruiseRoute
  DiscoverRoute: typeof DiscoverRoute
  EventsRoute: typeof EventsRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  GroupsRoute: typeof GroupsRouteWithChildren
  NRoute: typeof NRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PremiumRoute: typeof PremiumRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SafetyRoute: typeof SafetyRoute
  SettingsRoute: typeof SettingsRoute
  VisitorsRoute: typeof VisitorsRoute
  LegalBusinessTermsRoute: typeof LegalBusinessTermsRoute
  LegalCommunityRoute: typeof LegalCommunityRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalDsaRoute: typeof LegalDsaRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalSecurityIncidentsRoute: typeof LegalSecurityIncidentsRoute
  LegalSubprocessorsRoute: typeof LegalSubprocessorsRoute
  LegalTermsRoute: typeof LegalTermsRoute
  MessagesIdRoute: typeof MessagesIdRoute
  USlugRoute: typeof USlugRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  ApiPublicGooglePlayRtdnRoute: typeof ApiPublicGooglePlayRtdnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visitors': {
      id: '/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof VisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n': {
      id: '/n'
      path: '/n'
      fullPath: '/n'
      preLoaderRoute: typeof NRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruise': {
      id: '/cruise'
      path: '/cruise'
      fullPath: '/cruise'
      preLoaderRoute: typeof CruiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$slug': {
      id: '/u/$slug'
      path: '/u/$slug'
      fullPath: '/u/$slug'
      preLoaderRoute: typeof USlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$id': {
      id: '/messages/$id'
      path: '/messages/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/subprocessors': {
      id: '/legal/subprocessors'
      path: '/legal/subprocessors'
      fullPath: '/legal/subprocessors'
      preLoaderRoute: typeof LegalSubprocessorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/security-incidents': {
      id: '/legal/security-incidents'
      path: '/legal/security-incidents'
      fullPath: '/legal/security-incidents'
      preLoaderRoute: typeof LegalSecurityIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/dsa': {
      id: '/legal/dsa'
      path: '/legal/dsa'
      fullPath: '/legal/dsa'
      preLoaderRoute: typeof LegalDsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/community': {
      id: '/legal/community'
      path: '/legal/community'
      fullPath: '/legal/community'
      preLoaderRoute: typeof LegalCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/business-terms': {
      id: '/legal/business-terms'
      path: '/legal/business-terms'
      fullPath: '/legal/business-terms'
      preLoaderRoute: typeof LegalBusinessTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$id': {
      id: '/groups/$id'
      path: '/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof GroupsIdRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/advertise/new': {
      id: '/advertise/new'
      path: '/new'
      fullPath: '/advertise/new'
      preLoaderRoute: typeof AdvertiseNewRouteImport
      parentRoute: typeof AdvertiseRoute
    }
    '/api/public/google-play-rtdn': {
      id: '/api/public/google-play-rtdn'
      path: '/api/public/google-play-rtdn'
      fullPath: '/api/public/google-play-rtdn'
      preLoaderRoute: typeof ApiPublicGooglePlayRtdnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdvertiseRouteChildren {
  AdvertiseNewRoute: typeof AdvertiseNewRoute
}

const AdvertiseRouteChildren: AdvertiseRouteChildren = {
  AdvertiseNewRoute: AdvertiseNewRoute,
}

const AdvertiseRouteWithChildren = AdvertiseRoute._addFileChildren(
  AdvertiseRouteChildren,
)

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface GroupsRouteChildren {
  GroupsIdRoute: typeof GroupsIdRoute
}

const GroupsRouteChildren: GroupsRouteChildren = {
  GroupsIdRoute: GroupsIdRoute,
}

const GroupsRouteWithChildren =
  GroupsRoute._addFileChildren(GroupsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdvertiseRoute: AdvertiseRouteWithChildren,
  AuthRoute: AuthRoute,
  BlockedRoute: BlockedRoute,
  BusinessRoute: BusinessRoute,
  CruiseRoute: CruiseRoute,
  DiscoverRoute: DiscoverRoute,
  EventsRoute: EventsRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  GroupsRoute: GroupsRouteWithChildren,
  NRoute: NRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PremiumRoute: PremiumRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SafetyRoute: SafetyRoute,
  SettingsRoute: SettingsRoute,
  VisitorsRoute: VisitorsRoute,
  LegalBusinessTermsRoute: LegalBusinessTermsRoute,
  LegalCommunityRoute: LegalCommunityRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalDsaRoute: LegalDsaRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalSecurityIncidentsRoute: LegalSecurityIncidentsRoute,
  LegalSubprocessorsRoute: LegalSubprocessorsRoute,
  LegalTermsRoute: LegalTermsRoute,
  MessagesIdRoute: MessagesIdRoute,
  USlugRoute: USlugRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  ApiPublicGooglePlayRtdnRoute: ApiPublicGooglePlayRtdnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
